name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.svg
          user: miralemzhang
          template: classic
          config_timezone: Asia/Shanghai
          
          # 基础信息
          base: header, activity, repositories
          
          # 语言统计
          plugin_languages: yes
          plugin_languages_limit: 6
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_threshold: 1%
          
          # 贡献日历
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          # ===== 禁用以下插件 =====
          plugin_habits: no
          plugin_topics: no
          plugin_stars: no
          plugin_starlists: no
          plugin_followup: no
          plugin_activity: no
